### ISSUE TITLE
Invalid isoformat string

### ISSUE THREAD

**Issue by anderssv** [Danielhiversen/home_assistant_airthings_cloud#34]
Just installed through HACS and set up config. The logs fails in setup like this:

`Logger: homeassistant.components.sensor
Source: custom_components/airthings_cloud/sensor.py:99
Integration: Sensor (documentation, issues)
First occurred: 21 September 2021, 19:00:12 (2 occurrences)
Last logged: 21 September 2021, 19:00:12

Error adding entities for domain sensor with platform airthings_cloud
Error while setting up airthings_cloud platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/airthings_cloud/sensor.py", line 99, in device_state_attributes
    "timestamp": datetime.datetime.fromisoformat(
ValueError: Invalid isoformat string: ''
`

**Comment by Danielhiversen** [comment]
The Airthings integration will be part of the Home Assistant 2021.10, then you do not need the custom integration anymore

**Comment by anderssv** [comment]
Nice. But... How do I uninstall? There's no option in the HACS menu that says uninstall like in the other HACS integrations.
